### ISSUE TITLE
formatting of mobile version

### ISSUE THREAD

**Issue by oberon2007** [i3/i3.github.io#10]
In the mobile version (at least on a small screen like a Samsung Galaxy S3-mini) the buttons 'comment', 'edit', 'flag... are overlapping and are not usable.
Also 'sign out' is cut off and 'help' not present at all - it is probably outside the screen...

**Comment by stapelberg** [comment]
Which URL are you talking about?

**Comment by oberon2007** [comment]
faq.i3wm.org
The 'give feedback' link points to here! :)

**Comment by oberon2007** [comment]
Using the page in landscape mode helps partly but mentioned buttons are still not usable.

**Comment by stapelberg** [comment]
I see. It’s a bit unclear in the upstream software package we’re using, but technical feedback (as opposed to feedback about the actual content) on the FAQ software should go to http://askbot.org/en/questions/, so please report the issue you’re seeing directly at askbot. Thanks!

**Comment by oberon2007** [comment]
ok

**Comment by oberon2007** [comment]
Their feedback page is broken. The Captcha entered correctly is not accepted. So just you know that the problem remains unreported, sorry.

**Comment by stapelberg** [comment]
Try posting it as a question on their site instead.

**Comment by oberon2007** [comment]
I'm not convinced that it is my problem... ;)

**Comment by stapelberg** [comment]
You’re absolutely correct in that the broken feedback mechanism on askbot.com is not your problem. Nevertheless, I’d like to ask you to bring the issue you’re seeing on your device to the askbot developer’s attention so that they can fix it for your benefit and the benefit of other users. The only way to reach them that I know of is to post on their site. Thanks in advance for considering it.

**Comment by oberon2007** [comment]
I would have thought that the functionality of your faq-page is in your interest even more thatn mine, so I was a bit surprised and taken aback by the tone of your first replies.
Done anyway: http://askbot.org/en/question/13328/formatting-of-mobile-version-of-askbot-site/
and also: http://askbot.org/en/question/13329/captcha-check-for-feedback-on-askbotorg-broken/
greetings.

**Comment by Airblader** [comment]
We are a community driven project. It's part of the spirit that people contribute, even with things like big reports. 

It's you (and us and everyone else) who want to use the software and the website. Michael doesn't need the faq, he knows his software quite well. 

It's just the spirit you will find a lot in the Unix world. And I find it quite comforting.

**Comment by oberon2007** [comment]
sure. understood. i think the same.

**Comment by acrisci** [comment]
Report bugs here:

https://github.com/ASKBOT/askbot-devel

**Comment by stapelberg** [comment]
Thanks for taking the time to report both issues, and sorry that my tone came across as offputting in the first replies. I think my frustration with askbot is showing — it could be better maintained, but it’s the best FOSS forum in stackoverflow-style.

**Comment by oberon2007** [comment]
It's fine and thank you for replying again, Michael! :)

**Comment by oberon2007** [comment]
https://github.com/ASKBOT/askbot-devel/issues/495
