### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by iblue** [i3/i3.github.io#105]
I took the Logo SVG from this repo for my keyboard layout, which i published (https://github.com/iblue/neoqwertz-keyboard). Could you please add a license to your repo and the logo or tell me otherwise if this is acceptable use?

**Comment by stapelberg** [comment]
Open the logo SVG in a text editor, it contains a creative commons license:
```

<cc:license
--
  | rdf:resource="http://creativecommons.org/licenses/by-sa/3.0/" />


```
