### ISSUE TITLE
simple Chinese translation of userguide

### ISSUE THREAD

**Issue by zjuyk** [i3/i3.github.io#109]
Hello, we have made a simple Chinese translation of i3wm User's Guide.

Here is the [repo](https://github.com/zjuyk/i3wm-userguide-zh) and [preview](https://zjuyk.site/i3wm-userguide-zh/).

BTW, we used mdbook to generate the site instead of asciidoc.

**Comment by stapelberg** [comment]
Thanks! We’re tracking getting our infrastructure for translations improved in https://github.com/i3/i3/issues/4327, I’ll circle back to this translation when I get a chance to continue with that…

**Comment by zjuyk** [comment]
I switch to wayland and no longer to use i3wm. So, archived this translation repo.
