### ISSUE TITLE
Sur5r repository instructions are out of date

### ISSUE THREAD

**Issue by richlanc** [i3/i3.github.io#115]
The instructions for installing i3wm for ubuntu from the Sur5r repo are out of date as the key seemingly expired 2022-02-2.

@sur5r

**Comment by sur5r** [comment]
Uh, that's odd. The key should expire 2022-03-08. I was planning to update the keyring package. What does `apt-key list`say on your machine?

**Comment by richlanc** [comment]
Apologies @sur5r, I jumped to a conclusion. 
I saw the date on the keyring file and previously had issues with it going out of date. Looking more closely at our build logs, we experienced a brownout attempting to get the key.
