### ISSUE TITLE
Add Ctrl to the available modifiers

### ISSUE THREAD

**Issue by lasers** [i3/i3.github.io#12]
I found out about this easter egg today. It isn't mentioned anywhere on the i3wm docs.

Should we replace Mod1-Mod5 to Mod1, Mod2, Mod3, Mod4, Mod5 to make it more clear?

**Comment by stapelberg** [comment]
Well, `Control` is the preferred way of referring to that notifier, and `ctrl` is an alias we added. I’m okay with adding Ctrl, and also with expanding the list of modifiers. Note that the change will need to be done in https://github.com/i3/i3, file docs/userguide. Can you send a PR please?

**Comment by lasers** [comment]
Done.
