### ISSUE TITLE
sur5r-keyring_2022.02.17_all.deb getting 403  Forbidden

### ISSUE THREAD

**Issue by richlanc** [i3/i3.github.io#120]
https://i3wm.org/docs/repositories.html#:~:text=2.1.%20Stable%20releases

@sur5r The officially suggested method of installation for ubuntu is currently failing with a 403 error code when attempting to download the sur5r keyring.

**Comment by sur5r** [comment]
Fixed, sorry for the inconvenience.

**Comment by richlanc** [comment]
No worries, thanks for the quick fix and providing the infrastructure!
