### ISSUE TITLE
ubuntu repo notice for i386

### ISSUE THREAD

**Issue by metebalci** [i3/i3.github.io#121]
When using ubuntu repo, apt update shows notice because -I think- there is no i386 build:
```
N: Skipping acquire of configured file 'universe/binary-x86_64/Packages' as repository 'http://debian.sur5r.net/i3 focal InRelease' doesn't support architecture 'x86_64'
```
Would it be good (and work for armhf too) to add something like `[arch='dpkg-architecture | grep DEB_HOST_ARCH= | cut -f2 -d_']` to `echo "deb http://debian.sur5r.net/i3/...` command in the instructions ?

**Comment by sur5r** [comment]
`x86_64` is not a valid `DEB_HOST_ARCH`.

What does `dpkg --print-foreign-architectures` and `dpkg --print-architecture` return for you?

**Comment by sur5r** [comment]
Well, I see you point.

But given Ubuntu has stopped doing i386 altogether, I see no point in further complicating the installation instructions. Anyone having i386 enabled on focal and later will know why they are doing this and should know, how to adjust their sources.list accordingly.

I could add an empty i386 architecture to the repo to make the warning go away, but I fear this will only add confusion.

**Comment by stapelberg** [comment]
Sounds good, thanks for taking a look. I’ll close this issue.

**Comment by metebalci** [comment]
I realized this is already raised with i3/i3#4550
