### ISSUE TITLE
add screenshot with gaps

### ISSUE THREAD

**Issue by Quantenzitrone** [i3/i3.github.io#122]
I think, now that i3 4.22 is out, there should also be a screenshot on the website showcasing the gaps, as it is quite a big design feature.

**Comment by stapelberg** [comment]
There already is one in https://i3wm.org/docs/userguide.html#gaps, but sure, we can add one to the screenshots section as well. Do you want to contribute one?

**Comment by stapelberg** [comment]
That’s fine. Feel free to send a PR to add your screenshot.
