### ISSUE TITLE
should i3 website "FAQ" link to a closed reddit?

### ISSUE THREAD

**Issue by ColinSweetland** [i3/i3.github.io#128]
Hello, 

I noticed the I3 website FAQ tab directly links to the i3wm reddit, which is closed (protesting removal of API), and they refer you to https://github.com/i3/i3/discussions to ask new questions.

Maybe it could be useful for some people to look for old questions, but if the subreddit is going to stay closed maybe their should be a better link for FAQs.

**Comment by orestisfl** [comment]
No :laughing:. Thank you for noticing.
