### ISSUE TITLE
Remove "dynamic" TWM

### ISSUE THREAD

**Issue by Malix-off** [i3/i3.github.io#137]
_This issue is global to the organization, not specific to that repository_

## Problem

Currently, in the i3 organization, there are mention about i3 being a **"dynamic"** tiling window manager

> ### Code Search
> 
> - [**This repository**](https://github.com/search?q=repo%3Ai3%2Fi3.github.io%20dnyamic&type=code)
> - [**This organization**](https://github.com/search?q=org%3Ai3+dynamic&type=code)

I think it should be removed because that does not correspond to what a **"dynamic"** tiling window manager is

> ### Related
> 
> - https://github.com/i3/old-bugs.i3wm.org/blob/6f8d6adfa6d50eca8d7de1564bf8804f76386d49/report/ticket/674.html#L392
> - https://jeromebelleman.gitlab.io/posts/productivity/i3/#is-i3-a-manual-tiling-window-manager-though

## Solution

Removing the mentions about i3 being a **"dynamic"** tiling window manager

## Cross-repositories Pull Requests

- [ ] https://github.com/i3/i3/pull/6193
- [ ] https://github.com/i3/i3.github.io/pull/136
- [ ] https://github.com/i3/i3lock/pull/360
- [ ] https://github.com/i3/i3status/pull/532
- [ ] https://github.com/i3/build.i3wm.org/pull/2

**Comment by orestisfl** [comment]
No opinion on manual/dynamic, I'll let @stapelberg decide but regarding your blog post, the preferred way to do most of your red squares in i3 is with the IPC interface. For example, the "next workspace" is quite trivial: https://github.com/i3/i3/discussions/6147

**Comment by orestisfl** [comment]
On other points:
> It uses XCB, which not all systems support well. E.g. drawing the Geeqie window contents is noticeably slower than with xmonad.

i3 is not involved with drawing window contents. xcb is just a library implementing the same protocol Xlib is. That shouldn't be noticeable by windows at all.

**Comment by Malix-off** [comment]
Hello @orestisfl !

> regarding your blog post

I am not the author

**Comment by simlevesque** [comment]
> Currently, there are arguably misleading information about i3 being a dynamic tiling window manager

Prove it. You accuse someone of lying with absolutely zero proof. The blog post has no proof either, it's just stating that they think it's not dynamic, without any proof.

**Comment by Malix-off** [comment]
Hello @simlevesque ! : 

> Prove it.

See
- [Code Search](https://github.com/i3/i3.github.io/issues/137#issue-2442023488)
- https://github.com/i3/i3.github.io/pull/136/files

> You accuse someone of lying with absolutely zero proof.

I did not accused the i3 contributors to lie,
I asked if it was done on purpose or if there would be any reason to assert so, as maybe the i3 team identify that their product is indeed Dynamic

> It's just stating that they think it's not dynamic, without any proof.

i3 offers some flexibility in window management but still fundamentally operates on a manual basis by requiring direct user input for window layouts / behavior.

A dynamic tiling window manager usually automatically adjust window sizes and positions based on available screen space and set user preferences

Users must manually specify how windows are arranged (horizontal, vertical split, stacked, etc...) using keyboard shortcuts or configuration files;
By default, no automatic rearrangement based on window size or content changes are made automatically

Dynamic TWM also usually can use algorithms to anticipate user needs and automatically adjust window arrangements

> Honestly your tone is so bad that I would just close this issue for good.

Sorry about that, it was not my intention
Please feel free to edit the description and title to make it more inclusive

> then make another issue

Are you a member of i3 ?

> Your link even says that xmonad is dynamic, but you need to recompile it to change any settings, how it that dynamic ? It's the opposite of dynamic.

This does not contradict the meaning of a "Dynamic" tiling window manager

**Comment by stapelberg** [comment]
Of course we’re not lying on purpose, and that’s a pretty disrespectful accusation to just throw around. I recommend you assume good faith in future interactions.

i3 clearly isn’t dynamic in the sense that there is a fully automated window placement algorithm, but it also isn’t manual in the sense of TWM or ion3, where you had to select a destination for each new window, or in the sense of stacking window managers where windows just pop up whereever. Faced between the two extremes of manual and dynamic, I classified i3 more on the dynamic side than the manual side.

I can see that this classification is not entirely satisfying, but if we do anything about it, I would prefer to just get rid of the terms “manual” and “dynamic” entirely, as I don’t think they really help anyone. People should watch a video or try out i3 (or any other window manager, FWIW) to really get an impression of how it looks and behaves.

**Comment by Malix-off** [comment]
Hello @stapelberg !

> Of course we’re not lying on purpose, and that’s a pretty disrespectful accusation to just throw around. I recommend you assume good faith in future interactions.

It could sound offensive and aggressive, but I do not see marketing lie as such really, so no worries
I know a few projects and it's not that uncommon to see projects that intentionally lie about their marketing to attract more users, usually for a "greater good" (i.e. the most common form in the Linux world is "it just works")

> i3 clearly isn’t dynamic in the sense that there is a fully automated window placement algorithm, but it also isn’t manual in the sense of TWM or ion3, where you had to select a destination for each new window, or in the sense of stacking window managers where windows just pop up whereever. Faced between the two extremes of manual and dynamic, I classified i3 more on the dynamic side than the manual side.

Understandable

> I can see that this classification is not entirely satisfying, but if we do anything about it, I would prefer to just get rid of the terms “manual” and “dynamic” entirely, as I don’t think they really help anyone. 

That would indeed be better, reflecting it in #136 asap

> People should watch a video or try out i3 (or any other window manager, FWIW) to really get an impression of how it looks and behaves.

Agreed

**Comment by Malix-off** [comment]
_I just edited https://github.com/i3/i3.github.io/issues/137#issue-2442023488, it should be more appropriate and descriptive, now_
