### ISSUE TITLE
Spam on the faq page

### ISSUE THREAD

**Issue by Airblader** [i3/i3.github.io#15]
Since the outage a few days ago there seems to be a lot more spam. I'm deleting about two posts a day. 

Did anything not start up correctly or are we just seeing more spam?

**Comment by stapelberg** [comment]
It’s just more spam. There’s no locally-running spam filter or anything like that.

**Comment by Airblader** [comment]
Is there anything we can do to make it less? It's really getting out of hand at the moment. Or are we going to see if we can sit it out?

**Comment by stapelberg** [comment]
I wouldn’t know what. Recaptcha is enabled in askbot, I’m not sure why that’s not effective. Possibly there is a way to increase the difficulty? Check the source. Any changes would need to go through upstream, though.

**Comment by Airblader** [comment]
Yeah, that'd take a while if it happened at all. Can you maybe give me rights on the FAQ page? Through karma I can delete the posts (just now deleted like 8 or so again), but the users remain.

Maybe we can also see how they login and if they always use the same login service we can disable that one for a week or so?

**Comment by stapelberg** [comment]
You’re now an administrator.

**Comment by Airblader** [comment]
Thanks! Unfortunately there's a bug in the askbot release (fixed on master, though) that breaks sorting users by date, so I can't clean up all the created spam accounts for now. I'm getting all the new ones coming in now, though. :)
