### ISSUE TITLE
FAQ: Moderation 404

### ISSUE THREAD

**Issue by Airblader** [i3/i3.github.io#16]
Being an administrator now (thanks!) I get a notification for flagged posts, but clicking on it only yields a 404. I've found only one report about this on Askbot which didn't lead to anything (and hence I suspect this is fixed on master – maybe we just want to update to master?).

Is there any other way to get to those notifications?

**Comment by stapelberg** [comment]
Don’t know, sorry. Please ask upstream? :)

**Comment by Airblader** [comment]
Well it appears to be fixed upstream already, so we'd probably just be told to either update to master or wait for a release.
