### ISSUE TITLE
Spam on askbot

### ISSUE THREAD

**Issue by jkseppan** [i3/i3.github.io#17]
This is spam:

https://faq.i3wm.org/question/7068/kakim-sposobom-igrat-v-onlain-kazino-na-webmoney-i-inye-elektronnye-a-takzhe/

I'd downvote but that requires more karma.

**Comment by Airblader** [comment]
Yeah, but please don't report every spam post. There's up to a dozen per day. I don't want to just delete the spam but also the account that did it, which unfortunately doesn't work from the phone. 

Once we have the next update of Askbot, I'll have at least some better ways of dealing with this.
