### ISSUE TITLE
spam on faq

### ISSUE THREAD

**Issue by pniederlag** [i3/i3.github.io#18]
Some of these buttholes have added spam on https://faq.i3wm.org/
There a about 7 items all related to the term "cashback" that have been added today 2015-11-05.
Unfortunatly there's no "report spam" function for my karma.

**Comment by stapelberg** [comment]
Deleted. I think the “flag offense” function should be available to all registered users.

**Comment by Airblader** [comment]
It's available, but useless. We can't review those flags. It doesn't matter much, we don't have that much traffic to not see the spam ourselves. We actively remove spam already every day.
