### ISSUE TITLE
Contact page has incorrect freenode url.

### ISSUE THREAD

**Issue by kingy9000** [i3/i3.github.io#20]
The [i3 Contact Page](http://i3wm.org/contact/) (contact/index.html in the repo) has an incorrect url to freenode.net

It should be [https://www.webchat.freenode.net](https://www.webchat.freenode.net) not chat.freenode.net.

Suggest that you keep the https part as it defaults to unsecure http when not specified.

**Comment by Airblader** [comment]
We link to the IRC server, not some Web interface. It's up to the user which client they want to use.
