### ISSUE TITLE
FAQ Login not possible

### ISSUE THREAD

**Issue by Airblader** [i3/i3.github.io#4]
Sorry, Michael, didn't know a better place to put this. The FAQ was offline today and now I can't log in via Google anymore. It redirects to a Google page with an error:

> OpenID auth request contains an unregistered domain: http://i3faq:8080/

**Comment by stapelberg** [comment]
Thanks, I’m looking into it.

**Comment by stapelberg** [comment]
I think it should be working now. Can you confirm please, @Airblader?

**Comment by Airblader** [comment]
It does allow me to register now, but it seems it doesn't know about my old account anymore? It also seems that all comments from threads have disappeared.

**Comment by Airblader** [comment]
Looking at my Google apps I can see that my old account is connected to faq.i3wm.org and now I am connected to Faq.i3wm.org. I guess that makes a difference?

**Comment by stapelberg** [comment]
In https://security.google.com/settings/security/permissions?pli=1 I see “faq.i3wm.org” in “Account permissions”. Can you clarify what you used to see and what you see now? Just to be sure, you are only using a single google account, right?

**Comment by Airblader** [comment]
I see this: http://i.imgur.com/lvePf2L.png

I created a new account via email earlier and if I connect that one to Google, it shows up with "faq.i3wm.org" (lowercase 'F'). I'm currently unable to sign in with my previous account (from the screenshot). If I try to log in via Google, it just prompts me for access (= new account).

**Comment by Airblader** [comment]
Oh and please note that *all* comments (not just mine) seem to be gone right now.

**Comment by stapelberg** [comment]
Is the login problem reproducible for you? I don’t see migration-related messages in the askbot log, and I got them for my account.

**Comment by Airblader** [comment]
Sorry, what do you mean is the login problem reproducible? I don't get the error I initially reported anymore, but I still can't login with my actual account. Google instead asks me to grant permissions again and then creates a new account (and I can see both in the Account permissions – one with "Faq…", one with "faq…").

**Comment by stapelberg** [comment]
Does it work for you now?

**Comment by Airblader** [comment]
No. I can log in, but it creates a new account.

http://i.imgur.com/Oi9eKGd.png

**Comment by stapelberg** [comment]
Try clearing your cache. Porting a google account worked for me since I’ve changed the openid realm to be https://faq.i3wm.org/ (before it lacked the trailing slash). Not sure what else to do.

**Comment by Airblader** [comment]
Doesn't work either. Would it be possible for me to just create my new user and then you merge the two? See http://askbot.org/doc/management-commands.html

**Comment by Airblader** [comment]
If it is, the two accounts are

* "To user": https://faq.i3wm.org/users/24966/airblader/
* "From user": https://faq.i3wm.org/users/24653/airblader/ (will be deleted in the process)

**Comment by stapelberg** [comment]
@Airblader I’ve done this, but I’m not very happy with the result. It seems like the questions are still associated with your old (now blocked) UID. I think in the future, I’ll just change the associated login info and let people log into their old accounts, then delete the new and unused one.

**Comment by Airblader** [comment]
@stapelberg Thanks. I didn't think changing the association was possible (without weird manual database hacks anyway), so I searched for merging. It does seem odd that merging accounts ends this way, but as my colleagues like to say: "again what learned" ;)
