### ISSUE TITLE
build.i3wm.org lacking index/robots

### ISSUE THREAD

**Issue by jcf** [i3/i3.github.io#41]
The documentation for [`i3-msg`][] appears to have a broken link sending people to https://build.i3wm.org/, which then returns a GitHub pages 404 response.

![2018-01-17-21 19 51-b6a487b61098](https://user-images.githubusercontent.com/18374/35067556-33fe85be-fbcc-11e7-88b1-336f2f231604.png)

I think the problem is that you want the docs to show up at i3wm.org, but Google have found the same content on build.i3wm.org.

Here's an **example Google search result** in case that helps:

![2018-01-17-20 50 55-f9c26cccab06](https://user-images.githubusercontent.com/18374/35066421-687430e0-fbc8-11e7-9ab1-c38e8cf4a784.png)

To address the issue for humans you could set the [`href="/"`][] in question to "http://i3wm.org/" rather than just "/", but that's a bit of a hack (and might hurt your SEO).

…cue selling my friend's SEO consultancy… :wink:

### HTH!

[`href="/"`]: https://github.com/i3/i3.github.io/blob/bd35e39ee9370778c29af95c3d5d6a5b7f8d7bf6/docs/i3-msg.html#L21
[`i3-msg`]: https://build.i3wm.org/docs/i3-msg.html
[CNAME]: https://github.com/i3/i3.github.io/blob/bd35e39ee9370778c29af95c3d5d6a5b7f8d7bf6/CNAME

**Comment by snprajwal** [comment]
@Airblader @stapelberg can this documentation be added under the Developer section in i3 docs?

**Comment by stapelberg** [comment]
Sorry, I missed this when you originally reported it.

> To address the issue for humans you could set the [`href="/"`](https://github.com/i3/i3.github.io/blob/bd35e39ee9370778c29af95c3d5d6a5b7f8d7bf6/docs/i3-msg.html#L21) in question to "http://i3wm.org/" rather than just "/"

I think we should add an index page to build.i3wm.org, and also a robots.txt that removes it from search engines.

> @Airblader @stapelberg can this documentation be added under the Developer section in i3 docs?

What do you mean by “this documentation”? i3-msg? No, we don’t need to mention every single tool’s manpage explicitly from our main docs page. We could add 1 single link to https://manpages.debian.org/buster/i3-wm/index.html perhaps.

**Comment by stapelberg** [comment]
We now have a robots.txt. Adding an index file is a bit inconvenient due to how the build.i3wm.org repository is set up (generated by a script), so I’ll skip that for now.
