### ISSUE TITLE
Ubuntu APT instructions out of date

### ISSUE THREAD

**Issue by richlanc** [i3/i3.github.io#76]
/docs/repositories suggests installing ubuntu the package from Sur5r, but the described APT keyring is now missing (https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb).

**Comment by Airblader** [comment]
@sur5r This is just https://github.com/i3/i3/issues/3927 right?

**Comment by richlanc** [comment]
New instructions work.
