### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by acrisci** [i3/i3.github.io#8]
There should be a license for site resources (html, css, etc.) and maybe a separate one for content (copy and docs) if this is possible.

**Comment by stapelberg** [comment]
AFAIK, the creative commons licenses are typically used for licensing non-code parts of open source projects. Can you make a suggestion as to which flavor of creative commons license fits the BSD license we use in spirit?

Also, why do you say we should have a separate one for content/resources? I.e., what is the goal you intend to achieve with that?

**Comment by acrisci** [comment]
The faq might need to share some resources with the main site. The faq uses [cc-by-sa](http://creativecommons.org/licenses/by-sa/3.0/legalcode) for the license of its content.

I don't think there are any actual legal issues here, but it's a good idea to be specific about licensing so people don't have to ask.

There are some gray areas even wtih licensing. For instance, the i3wm subreddit uses the i3 logo which is not covered by any of the open source licenses, but I don't see that as an issue.

**Comment by stapelberg** [comment]
> For instance, the i3wm subreddit uses the i3 logo which is not covered by any of the open source licenses, but I don't see that as an issue.

https://raw.githubusercontent.com/i3/i3/next/logo.svg actually specifies a license:

    <cc:license rdf:resource="http://creativecommons.org/licenses/by-sa/3.0/" />

> The faq might need to share some resources with the main site. The faq uses cc-by-sa for the license of its content.

I suppose we should use CC-BY-SA 3.0 for the website itself then, considering that we already use it for the FAQ and the logo.

**Comment by Airblader** [comment]
So the logo has a license and this issue is quite stale, closing.
