### ISSUE TITLE
No direct links to tools

### ISSUE THREAD

**Issue by snprajwal** [i3/i3.github.io#99]
I noticed that there are no direct links from i3's website to tool pages like https://i3wm.org/i3status/ or https://i3wm.org/i3bar/. Should these be added under a separate "Tools" header or something? It can also links to i3-related projects as suggested in #9.

**Comment by stapelberg** [comment]
You added a link to i3status in commit be02b0bed3c2bc33da4685ff080027d71bb20f2d, thanks!

i3bar’s configuration is documented as part of the i3 userguide: https://i3wm.org/docs/userguide.html#_configuring_i3bar

The https://i3wm.org/i3bar/ website and https://i3wm.org/i3bar/manpage.html manpage are only pro forma, so do not need to be referenced prominently. The split of i3 and i3bar into separate executable programs should be an implementation detail with which regular users are not confronted :)
